---
functional:
  - Требование 1 Пользователь должен иметь возможность фильтровать товары и искать их по ключевому слову или категории
  - Требование 2 Пользователь должен иметь возможность просматривать сам товар и подробную информацию о нем
  - Требование 3 Пользователь должен иметь возможность добавлять товары в корзину и просматривать ее содержимое
non-functional:
  - Требование 4 Сайт нужно разработать с учетом удобства использования, оптимизировать для быстрой работы и оно должено быть безопасным и защищать данные ползователя
  - Требование 5 Сайт должен быть доступен на различных устройствах и иметь мобильную версию
  - Требование 7 Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Требование 8 Важно, чтобы сайт мог обрабатывать большое количество трафика 
implicit:
  - Требование 9 На главной странице должна быть кнопка регистрации, без регистрации у пользователя должны быть ограниченя по использованию сайта
  - Требование 10 Не зарегистрированные пользователи должны иметь возможность просматривать товары и подробную информацию о них
